---
title: "Structure of subgraphs results"
author: "Nick Strayer"
date: "6/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%")
library(dplyr)
library(tidyverse)
library(phewasHelper)
library(entropynet)

association_pairs <- virus_net %>% 
  arrange(desc(strength))
```


## Finding all subgraphs

First we will run subgraph finding algorithm across the associations

```{r, cache = TRUE}

components <- association_pairs %>% head(10000) %>% explore_component_structure()

components %>% 
  select(-components) %>% 
  head() %>% 
  knitr::kable()
```

## Visualizing subgraphs search

Next we can investigate the subgraph structure over search

```{r}

min_rel <- components %>%
  filter(rel_max_size == min(rel_max_size)) %>%
  tail(1)

max_num_components <- components %>%
  filter(n_components == max(n_components)) %>%
  tail(1)

max_num_triples <- components %>%
  filter(n_triples == max(n_triples)) %>%
  tail(1)

components %>%
  # filter(rel_max_size < 0.5) %>%
  select(
    strength,
    n_components,
    max_size,
    rel_max_size,
    avg_density,
    n_triples,
    step
  ) %>% 
  pivot_longer(-step) %>%
  ggplot(aes(x = step, y = value)) +
  geom_step() +
  geom_vline(xintercept = min_rel$step, color = 'orangered') +
  geom_vline(xintercept = max_num_components$step, color = 'forestgreen') +
  geom_vline(xintercept = max_num_triples$step, color = 'steelblue') +
  facet_grid(rows = vars(name), scales = "free_y")

```

```{r}
plot_component_info <- function(step_row, title) {
  step_row %>%
    pluck("components", 1) %>%
    arrange(-size,-strength) %>%
    mutate(id = forcats::fct_inorder(factor(id))) %>%
    ggplot(aes(
      x = id,
      y = size,
      fill = strength,
      alpha = density
    )) +
    geom_col() +
    theme_phewas() +
    labs(x = "component",
         title = title)
}

plot_component_info(min_rel, "Component structure for minimum relative cut")

nodes_info <- virus_host_viruses %>% 
  rename(id = virus_id) %>% 
  mutate(color = ifelse(type == "RNA", "orangered", "steelblue"))

visualize_association_network(
  association_pairs = head(association_pairs, min_rel$n_edges),
  node_info = nodes_info,
  measure_title = "relative smoothed mutual information",
  warn_of_mismatches = FALSE,
  alphaDecay = 0.01
)
```

```{r}
plot_component_info(max_num_components, "Component structure for max number of components")

visualize_association_network(
  association_pairs = head(association_pairs, max_num_components$n_edges),
  node_info = nodes_info,
  measure_title = "relative smoothed mutual information",
  warn_of_mismatches = FALSE,
  alphaDecay = 0.01
)
```


```{r}
plot_component_info(max_num_triples, "Component structure for max number of components larger than 2 nodes")

visualize_association_network(
  association_pairs = head(association_pairs, max_num_triples$n_edges),
  node_info = nodes_info,
  measure_title = "relative smoothed mutual information",
  warn_of_mismatches = FALSE,
  alphaDecay = 0.01
)
```
