# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find all components in pairs for every subset of edges (c++ version)
#'
#' Given a dataframe of edges with strength between nodes this function returns
#' info on every component state achieved by adding nodes in one-at-a-time in
#' descending order of strength.
#'
#' @param associations Dataframe of association between two ids with a strength
#' @param a_col,b_col Names of columns that store the id's for the association
NULL

#'
#' @export
find_components <- function(associations, a_col = "a", b_col = "b", w_col = "w") {
    .Call(`_entropynet_find_components`, associations, a_col, b_col, w_col)
}

edges_to_all_nodes <- function(a, b, n) {
    .Call(`_entropynet_edges_to_all_nodes`, a, b, n)
}

