# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_components <- function(a, b, w) {
    .Call(`_entropynet_find_components`, a, b, w)
}

edges_to_all_nodes <- function(a, b, n) {
    .Call(`_entropynet_edges_to_all_nodes`, a, b, n)
}

